name: Django CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10.6"]

    steps:
    - uses: actions/checkout@v2
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: graphviz libgraphviz-dev
        version: 1.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Lint with Flake8
      run: |
        flake8 . --ignore=F403,DJ01,F821,E501
    - name: Run Tests
      run: |
        python manage.py test